//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VultronOBU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trains
    {
        public int id { get; set; }
        public int trainnumber { get; set; }
        public string traintype { get; set; }
        public string endstation { get; set; }
    }
}
